### ISSUE TITLE
Update Telegram-Bot version

### ISSUE THREAD

**Issue by Skowt** [telegram-bot-rb/telegram_bot_app#12]
Noticed that we're looking at:
https://github.com/telegram-bot-rb/telegram_bot_app/blob/846063c7ebd2dec02135f024b31867b3fd137eee/Gemfile#L29

While the latest version seems to be: **v0.13.0 / c86b2ef**
https://github.com/telegram-bot-rb/telegram-bot/tags

Is there a reason not to upgrade to the latest available version?

**Comment by printercu** [comment]
Hi! Nope, it just required master at some point. I'll update to the latest version soon, there should be no issues with it.

**Comment by printercu** [comment]
Updated in 5e98e131220c98594a83ac27f05b9c8533572f89
