### ISSUE TITLE
Halt if unauthorized

### ISSUE THREAD

**Issue by Skowt** [telegram-bot-rb/telegram_bot_app#13]
I'm currently trying to implement some authentication for my Telegram users where I'll create them in a database the first time I see their ID + username and then update them or check if they're allowed to interact with the bot in the future.

However trying to do this in `TelegramWebhooksController` is proving very tricky. I'm trying to use a `before_filter` to prevent any actions from running unless the user is authenticated but I can't find a way of preventing the normal methods from running if that happens. 

I could create two separate controllers, one to authenticate vs one to run all the normal commands but that seems overkill when I just need one method for this. Do you have any secret ways of preventing methods running using a before_filter? I've tried using render or redirect but neither of them seem to be implemented.

**Comment by printercu** [comment]
Rails >= 5 uses `throw :abort` to stop executing callback chain. Previous versions used `return false`. Does this work for you?

**Comment by Skowt** [comment]
That's beautiful 🙌 Battled with this for much longer than I'd like to admit.
