### ISSUE TITLE
Send photo

### ISSUE THREAD

**Issue by Soloma1488** [telegram-bot-rb/telegram_bot_app#14]
Hello, first u have very cool telegram bot..
But i cant send photo maybe u can help me? Give me Any example plssss

**Comment by printercu** [comment]
Hi! With controller's reply helper:
```
reply_with :photo, photo: File.open('party.jpg')
```
Outside of controller:
```
bot.send_photo chat_id: chat_id, photo: File.open('path/to/file.jpg')
```
You can add any other available request fields as well. Note that sending photos is not possible in async mode. See telegram-bot readme for details.

**Comment by Soloma1488** [comment]
file is not important to indicate, just specify the path? I would also like to clarify how to add a description to the photo? that would be sent in one message.

**Comment by printercu** [comment]
> file is not important to indicate, just specify the path?

You need to pass a readable file object created with File.open

> I would also like to clarify how to add a description to the photo?

Looks like you need caption option. Please see description and other available options in official docs: 
https://core.telegram.org/bots/api#sendphoto

**Comment by Soloma1488** [comment]
Ty for u help and  your bot!!!! If u can send me you @mail or telegram for communication
