### ISSUE TITLE
Webhook not send message

### ISSUE THREAD

**Issue by muhrizkiakbar** [telegram-bot-rb/telegram_bot_app#15]
I was follow your documentation and Webhook setting is done in production, but the bot didnt send any message

**Comment by printercu** [comment]
Does it work in development?

**Comment by muhrizkiakbar** [comment]
yess, work nicely in development

I try to restart my server, and the bot runs but only briefly, about 30 seconds

**Comment by muhrizkiakbar** [comment]
this is my setting in production environment

routes.default_url_options = {host: 'corona.kalselprov.go.id', protocol: 'https'}
config.telegram_updates_controller.session_store = :file_store,
Rails.root.join('tmp', 'session_store')

**Comment by muhrizkiakbar** [comment]
I dont use daemon gem, I just follow the instructions here [https://github.com/telegram-bot-rb/telegram_bot_app](url)

**Comment by printercu** [comment]
Have `bin/rake telegram:bot:set_webhook RAILS_ENV=production` been finished successfully?

**Comment by muhrizkiakbar** [comment]
yess, i have and finished successfully

**Comment by muhrizkiakbar** [comment]
here is the my username bot
@covid19_kalsel_bot

**Comment by muhrizkiakbar** [comment]
[production.rb.zip](https://github.com/telegram-bot-rb/telegram_bot_app/files/4528946/production.rb.zip)
[session_store.rb.zip](https://github.com/telegram-bot-rb/telegram_bot_app/files/4528949/session_store.rb.zip)

**Comment by muhrizkiakbar** [comment]
<img width="768" alt="Screen Shot 2020-04-24 at 8 55 02 PM" src="https://user-images.githubusercontent.com/18720002/80214713-e6cd6880-866d-11ea-9b18-57e858120239.png">

**Comment by printercu** [comment]
Please try `bot.get_webhook_info`. It should show webhook delivery error if any.

**Comment by muhrizkiakbar** [comment]
in rails console?

**Comment by muhrizkiakbar** [comment]
![photo_2020-04-24 21 10 06](https://user-images.githubusercontent.com/18720002/80216021-ff3e8280-866f-11ea-9b55-10b88bdf5d26.jpeg)

**Comment by printercu** [comment]
It looks like there were errors, telegram can stop sending webhooks because of it. Check your rails logs for the errors (or I better suggest to use rollbar/sentry), fix if any, then run rake task to set webhook again, to make telegram reset error status.

**Comment by muhrizkiakbar** [comment]
Update: {"update_id":xxxx,"message":{"message_id":xxxxx,"from":{"id":xxxxx,"is_bot":false,"first_name":"xxxxx","last_name":"xxxxxxx"},
"chat":{"id":-xxxxxx,"title":"Tes Prov. Kalsel","**type**":"supergroup"}, <<<< this
"date":1587790866,
"text":"/menu@xxxxxx",
"entities":[{"offset":0,"length":24,"type":"bot_command"}]
}}

how to get object chat type to make sure that must chat type is PRIVATE?

**Comment by printercu** [comment]
`payload.dig('chat', 'type') == 'private'`

**Comment by muhrizkiakbar** [comment]
> `payload.dig('chat', 'type') == 'private'`

thanks
