### ISSUE TITLE
Cannot start production

### ISSUE THREAD

**Issue by zhum** [telegram-bot-rb/telegram_bot_app#2]
I try to run bot server. In development mode it works fine, but I cannot start it in production mode:

```
serg@asi ~/tmp/telegram_bot_app-master $ bin/rake --trace telegram:bot:set_webhook RAILS_ENV=production
Running via Spring preloader in process 25373
** Invoke telegram:bot:set_webhook (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute telegram:bot:set_webhook
rake aborted!
ArgumentError: Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true
/home/serg/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.6/lib/action_dispatch/http/url.rb:45:in `full_url_for'
/home/serg/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.6/lib/action_dispatch/http/url.rb:35:in `url_for'
/home/serg/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/route_set.rb:354:in `block in <class:RouteSet>'
/home/serg/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/route_set.rb:221:in `call'
/home/serg/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/route_set.rb:221:in `call'
/home/serg/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/route_set.rb:345:in `block (2 levels) in define_url_helper'
/home/serg/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/telegram-bot-995cde5607b9/lib/tasks/telegram-bot.rake:22:in `block (4 levels) in <top (required)>'
/home/serg/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/telegram-bot-995cde5607b9/lib/tasks/telegram-bot.rake:20:in `each'
/home/serg/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/telegram-bot-995cde5607b9/lib/tasks/telegram-bot.rake:20:in `block (3 levels) in <top (required)>'
/home/serg/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/task.rb:248:in `call'
/home/serg/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/task.rb:248:in `block in execute'
/home/serg/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `each'
/home/serg/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `execute'
/home/serg/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
/home/serg/.rbenv/versions/2.2.2/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/home/serg/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/task.rb:180:in `invoke_with_call_chain'
/home/serg/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/task.rb:173:in `invoke'
/home/serg/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/application.rb:152:in `invoke_task'
/home/serg/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/home/serg/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `each'
/home/serg/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block in top_level'
/home/serg/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/application.rb:117:in `run_with_threads'
/home/serg/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/application.rb:102:in `top_level'
/home/serg/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/application.rb:80:in `block in run'
/home/serg/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'
/home/serg/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/application.rb:77:in `run'
/home/serg/tmp/telegram_bot_app-master/bin/rake:9:in `<top (required)>'
/home/serg/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
/home/serg/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `block in load'
/home/serg/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/serg/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
/home/serg/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/home/serg/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
-e:1:in `<main>'
Tasks: TOP => telegram:bot:set_webhook
```

Also I cannot understand how to start application if I want to use the bot together with regular rails application (I want to send to connected users messages when something happens on website).

**Comment by printercu** [comment]
https://github.com/telegram-bot-rb/telegram-bot/issues/13

**Comment by printercu** [comment]
Basically you don't need anything else to run bot with rails app, just setup webhook to receive updates.
If you don't want to use webhook, you need to run this rake task.

**Comment by zhum** [comment]
Thanks! Ticket#13 helped :)  But now it does not respond to any requests via telegram... How can I debug it? May be just check is it registered in telegram or not?

**Comment by printercu** [comment]
Have you set webhook up? https://github.com/telegram-bot-rb/telegram_bot_app#production

**Comment by printercu** [comment]
Have you setup webhook with real domain? Do you see webhook requests in the webserver log?

**Comment by zhum** [comment]
The domain is real, it has 'white' ip address, no firewalls.
No, I see nothing. Bot simply shows regular rails prologue (... INFO  WEBrick::HTTPServer#start: pid=25775 port=3000) then nothing happens. If I send commands or anything to bot, I get nothing back. logs/production.log is just empty.
API token works, I've tested it with telegram_bot gem.

**Comment by printercu** [comment]
Do you have nginx or anything else in front of rails? If so, check its log.
If not: Your rails app is running on 3000 port, you need to specify it in `default_url_options` along with host. To check current url options you can run `Rails.application.routes.url_helpers.telegram_webhook_url` in your **production** console.

**Comment by zhum** [comment]
I've added 'port: 3000' to default_url_options, but no effect. It still works if I run `bundle exec bin/rake telegram:bot:poller`, but in this mode default routing does not work, so I cannot create API...

**Comment by printercu** [comment]
Have you run set_webhook, after adding port option? Is your rails app accessible from the internet, can you open URL in your browser, so the request is logged by rails? Have you checked webhook URL with the command from my previous comment?

Do you use different tokens for prod & dev? I hope you message to different bots too.

**Comment by zhum** [comment]
Tried  with webhooks. No success. I added one simple model 'event' with controller. Changed port to 8433, ran  set_webhook. Now I can start it in production mode, but. If I try to connect to localhost:8443/events, I get message 'Something went wrong' (and NO logged messages!). While app is working I get error log records like this:

```
serg@asi ~/tmp/111/lom_bot $ bundle exec rails s -e production -p 8443
=> Booting WEBrick
=> Rails 5.0.0.1 application starting in production on http://0.0.0.0:8443
=> Run `rails server -h` for more startup options
[2016-12-30 12:23:58] INFO  WEBrick 1.3.1
[2016-12-30 12:23:58] INFO  ruby 2.2.2 (2015-04-13) [x86_64-linux]
[2016-12-30 12:23:58] INFO  WEBrick::HTTPServer#start: pid=9373 port=8443
[2016-12-30 12:23:59] ERROR bad Request-Line `\x16\x03\x01\x01N\x01\x00\x01J\x03\x03���|�"�\x03\x11d=�K�\r@�� o?�ܠ�<��\\\e�e\x00\x00��0�,�(�$�\x14�'.
[2016-12-30 12:24:01] ERROR bad URI `�Be�\x00\x00��0�,�(�$�\x14�'.

```

I set force_ssl option to 'true', but nothing changed. I generated ssl keys, but have no idea how to specify them in command line.

I use the same tokens for prod & dev (just like in example app).
telegram_webhook_url looks like this: http://MY_SERVER_NAME:8443/telegram/291277135_AAGKAQmBdpJcCZplJM6bgwu5K5rsypFoNxA

**Comment by printercu** [comment]
I think it's not related to telegram-bot or this application. Please try to google or search/ask questions on StackOverflow. Here some notes from me:

- Rails doesn't log to stdout in production. Check `log/production.log` for errors.
- Try add `gem 'puma'` to `Gemfile`. Rails 5 uses it by default, I'll update Gemfile to. Maybe there are some issues with webrick.
- Try setup new app from scratch with https://github.com/telegram-bot-rb/rails_template. Its readme contains all instructions. I've deployed one similar not so long ago.
- I don't use rails without nginx in production, so can't help with setting up ssl in rails. nginx does all ssl stuff for me.

**Comment by printercu** [comment]
Closing due to no feedback. Feel free to ping me here to reopen.
