### ISSUE TITLE
What about CHANGELOG? 

### ISSUE THREAD

**Issue by vovs03** [telegram-bot-rb/telegram_bot_app#26]
# :memo: What about CHANGELOG?

> `question`

:star: Will you planning to write this `CHANGELOG` file?
It's interesting to watch & know what was did. Thank you

**Comment by printercu** [comment]
This repo is not expected to be updated a lot (or even at all), so I think no changelog or versioning is necessary. Please see commit messages for details.

**Comment by vovs03** [comment]
Ok, @printercu thank you.
