### ISSUE TITLE
Clear messages history

### ISSUE THREAD

**Issue by yuri-karpovich** [telegram-bot-rb/telegram_bot_app#29]
Hello!

I'm looking for an ability to clear all messages in all chats on a daily basis.  I store all user messages with  `before_action :save_message_id` callback but I'm stuck how to save all bot messages. Can you help me please!

**Comment by printercu** [comment]
Hi! Every call to API returns response from telegram. There should be an id of created message.

**Comment by yuri-karpovich** [comment]
Got it. Then I need to find every message in my code and process each of them manually.
