### ISSUE TITLE
Get message data from cmd methods

### ISSUE THREAD

**Issue by SergiiVdovareize** [telegram-bot-rb/telegram_bot_app#3]
Hi
I see you pass the message data to the `message` method only: `def message(message)` - [code](https://github.com/telegram-bot-rb/telegram_bot_app/blob/master/app/controllers/telegram_webhooks_controller.rb#L72)
But how to get it from any cmd method? For example from `memo`: `def memo(*args)` - [code](https://github.com/telegram-bot-rb/telegram_bot_app/blob/master/app/controllers/telegram_webhooks_controller.rb#L22)

Thanks

**Comment by printercu** [comment]
Hi, there is `#payload` method for this. Take a look at telegram-bot's readme for more info (https://github.com/telegram-bot-rb/telegram-bot#controller).

**Comment by SergiiVdovareize** [comment]
Thanks a mil
