### ISSUE TITLE
Poller vs Rails server

### ISSUE THREAD

**Issue by julesmaregiano** [telegram-bot-rb/telegram_bot_app#43]
Sorry for the noob question, but I have a hard time understanding why we need to use the `telegram:bot:poller` command, instead of the usual `rails server`?

Wouldn't it be easier for developers to stick to the usual `rails server`? How can I do that? Thanks for your help :pray:

**Comment by printercu** [comment]
Hey. Here is comparison https://github.com/telegram-bot-rb/telegram-bot/wiki/Deployment

To use rails server for development you need public ip for your development machine to receive requests from telegram. Wiki has example how to use self-signed certificates if you decide to go this way.

**Comment by julesmaregiano** [comment]
Thanks a lot
