### ISSUE TITLE
How to invoke new keyboard on button click

### ISSUE THREAD

**Issue by kirantpatil** [telegram-bot-rb/telegram_bot_app#9]
Hi,

How and where should I add code to invoke a new keyboard from existing keyboard on clicking a button?

Thanks.

**Comment by printercu** [comment]
Hi. There are different keyboard types. See https://github.com/telegram-bot-rb/telegram_bot_app/blob/master/app/controllers/telegram_webhooks_controller.rb#L29-L41 for usual keyboard, and https://github.com/telegram-bot-rb/telegram_bot_app/blob/master/app/controllers/telegram_webhooks_controller.rb#L43-L61 for inline keyboards. Just send new keyboard when receive click from previous one. You can either send new message or edit previous one (see helpers in https://github.com/telegram-bot-rb/telegram-bot/blob/master/lib/telegram/bot/updates_controller/reply_helpers.rb#L33-L54).

Before you start, make sure you've read telegram guides and examples about keyboards.

**Comment by printercu** [comment]
Did it help? Can we close this one?

**Comment by kirantpatil** [comment]
Sorry @printercu, I haven't tried it, since I was busy in other work. 

Anyway I will close the issue since it has the pointers.

Thanks.
